jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew check -PjdkVersion=11 --no-daemon --refresh-dependencies
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___test-gradle.yml
permissions: {}
